
import javax.swing.JOptionPane;


public class SignInFrom extends javax.swing.JFrame {

    /**
     * Creates new form SignInFrom
     */
    public SignInFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        UserName = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        User = new javax.swing.JTextField();
        PassField = new javax.swing.JPasswordField();
        Submit = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        Type = new javax.swing.JComboBox<>();
        UserType = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sing in Page");
        setLocation(new java.awt.Point(350, 150));
        setPreferredSize(new java.awt.Dimension(800, 450));
        setSize(new java.awt.Dimension(852, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton.setBackground(new java.awt.Color(128, 113, 203));
        BackButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        UserName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 225, 230));
        UserName.setText("User Name :");
        getContentPane().add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 110, 30));

        Password.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 225, 230));
        Password.setText("Password :");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 100, 20));

        User.setBackground(new java.awt.Color(185, 191, 190));
        User.setToolTipText("Enter your name");
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 140, -1));

        PassField.setBackground(new java.awt.Color(185, 191, 190));
        PassField.setToolTipText("Enter Your Password");
        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 140, -1));

        Submit.setBackground(new java.awt.Color(179, 225, 220));
        Submit.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Submit.setForeground(new java.awt.Color(32, 110, 132));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        CancelButton.setBackground(new java.awt.Color(179, 225, 220));
        CancelButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(32, 110, 132));
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        Type.setBackground(new java.awt.Color(0, 13, 21));
        Type.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Type.setForeground(new java.awt.Color(0, 48, 74));
        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expert", "General" }));
        Type.setToolTipText("For asking a question use General.");
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });
        getContentPane().add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 120, -1));

        UserType.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        UserType.setForeground(new java.awt.Color(255, 225, 230));
        UserType.setText("User Type :");
        getContentPane().add(UserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 276, 90, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\NetBeansProjects\\JavaProject\\JavaProject\\src\\forumhome\\MyIcon\\sign1.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 450));

        pack();
    }// </editor-fold>                        

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        dispose();
        ForumHome forum = new ForumHome() ;
        forum.setVisible(true);
    }                                            

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        dispose();
        ForumHome forum = new ForumHome() ;
        forum.setVisible(true);
    }                                          
    Object comboSelected;
    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        
        
        
    }                                    

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        dispose();
        String type = (String)Type.getSelectedItem();
        //JOptionPane.showMessageDialog(null, comboSelected.toString());
        String name = User.getText();
        String pass = PassField.getText();
        if(MyDataBaseCon.check(name, pass, type))
        {
        if(type.equals("Expert"))
        {
            expertAns aandq = new expertAns(name,type);
             new expertAns().setVisible(true);
        }
        else
        {
             QuesAndAns qna= new QuesAndAns(name,type);
             qna.setVisible(true);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Wrong Password or User Name\ntry again\n");
            new SignInFrom().setVisible(true);
        }
    }                                      

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInFrom().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JLabel Password;
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JTextField User;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel UserType;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration                   

    private Object ExpertAns() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
